# Generated by Django 2.1 on 2018-12-24 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20181220_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='webapp.Food', verbose_name='Блюдо')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foods', to='webapp.Order', verbose_name='Заказ')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderfoods',
            name='food',
        ),
        migrations.RemoveField(
            model_name='orderfoods',
            name='order',
        ),
        migrations.DeleteModel(
            name='OrderFoods',
        ),
    ]
