# Generated by Django 2.1 on 2018-12-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20181224_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('change_status', 'Изменение заказа')]},
        ),
    ]
