# Generated by Django 2.1 on 2018-12-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181227_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('change_status', 'Изменение заказа'), ('canceled_order', 'Отмена заказа')]},
        ),
    ]
